name: perform-release
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm install --frozen-lockfile
      - run: npm run test
      - run: npm build
